name: PR Emojis in Slack

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-emojis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_BOT_USER_ID: ${{ vars.SLACK_BOT_USER_ID }}
