name: PR Emojis in Slack

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [closed]

permissions: {}

jobs:
  pr-emojis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_CHANNEL_ID: C06P2KX149M
          SLACK_API_TOKEN: ${{ secrets.SLACK_TOKEN }}
          BOT_USER_ID: UTMS06TPX
